name: Download Archive
description: Downloads and decompresses an archive from a previous job
inputs:
  path:
    description: location to decompress the archive to
    default: .
runs:
  using: 'composite'
  steps:
    - name: Get Project Name
      id: repo-name
      run: |
        REPO_NAME=${GITHUB_REPOSITORY#*/}
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_OUTPUT
        echo "Repository name: $REPO_NAME"        
      shell: bash

    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: ${{ steps.repo-name.outputs.REPO_NAME }}
        path: ${{ inputs.path }}

    - name: Extract Archive
      run: unzip -q -o ${{ inputs.path }}/${{ steps.repo-name.outputs.REPO_NAME }}.zip
      shell: bash

    # Remove the ZIP file after we've extracted it - we don't want this committed back to the repo
    - name: Delete The Archive ZIP File
      run: rm ${{ inputs.path }}/${{ steps.repo-name.outputs.REPO_NAME }}.zip
      shell: bash