name: Get Core Dependencies
description: Sets the Node.js version and initializes core dependencies
inputs:
  node-version:
    description: Node.js version to use when preparing the publish environment.
    required: false
    default: '20'
  registry-url:
    description: Registry URL used for npm publish.
    required: false
    default: 'https://registry.npmjs.org'
    
runs:
  using: composite
  steps:
    # this overrides previous versions of the node runtime that was set.
    # jobs that need a different version of the Node runtime should explicitly
    # set their node version after running this step
    - name: 🟢 Use Node Version from .nvmrc
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          package.json
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: 📦 Install Dependencies
      run: npm install
      shell: bash
